apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-platformaccess
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: PlatformAccess
  plural: platformaccesses
  singular: platformaccess
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
