apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-platforminvitation
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: PlatformInvitation
  plural: platforminvitations
  singular: platforminvitation
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch


