apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-policybinding
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: PolicyBinding
  plural: policybindings
  singular: policybinding
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
