apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-serviceaccount
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: ServiceAccount
  plural: serviceaccounts
  singular: serviceaccount
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
