apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-userinvitation
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: UserInvitation
  plural: userinvitations
  singular: userinvitation
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
    - apiGroup: iam.miloapis.com
      kind: User
