//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Contact) DeepCopyInto(out *Contact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Contact.
func (in *Contact) DeepCopy() *Contact {
	if in == nil {
		return nil
	}
	out := new(Contact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Contact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroup) DeepCopyInto(out *ContactGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroup.
func (in *ContactGroup) DeepCopy() *ContactGroup {
	if in == nil {
		return nil
	}
	out := new(ContactGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupEnrollmentPolicy) DeepCopyInto(out *ContactGroupEnrollmentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupEnrollmentPolicy.
func (in *ContactGroupEnrollmentPolicy) DeepCopy() *ContactGroupEnrollmentPolicy {
	if in == nil {
		return nil
	}
	out := new(ContactGroupEnrollmentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupEnrollmentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupEnrollmentPolicyList) DeepCopyInto(out *ContactGroupEnrollmentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContactGroupEnrollmentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupEnrollmentPolicyList.
func (in *ContactGroupEnrollmentPolicyList) DeepCopy() *ContactGroupEnrollmentPolicyList {
	if in == nil {
		return nil
	}
	out := new(ContactGroupEnrollmentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupEnrollmentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupEnrollmentPolicySpec) DeepCopyInto(out *ContactGroupEnrollmentPolicySpec) {
	*out = *in
	out.ContactGroupRef = in.ContactGroupRef
	out.Trigger = in.Trigger
	if in.ContactSelector != nil {
		in, out := &in.ContactSelector, &out.ContactSelector
		*out = new(EnrollmentContactSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupEnrollmentPolicySpec.
func (in *ContactGroupEnrollmentPolicySpec) DeepCopy() *ContactGroupEnrollmentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ContactGroupEnrollmentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupList) DeepCopyInto(out *ContactGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContactGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupList.
func (in *ContactGroupList) DeepCopy() *ContactGroupList {
	if in == nil {
		return nil
	}
	out := new(ContactGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembership) DeepCopyInto(out *ContactGroupMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembership.
func (in *ContactGroupMembership) DeepCopy() *ContactGroupMembership {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipList) DeepCopyInto(out *ContactGroupMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContactGroupMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipList.
func (in *ContactGroupMembershipList) DeepCopy() *ContactGroupMembershipList {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipRemoval) DeepCopyInto(out *ContactGroupMembershipRemoval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipRemoval.
func (in *ContactGroupMembershipRemoval) DeepCopy() *ContactGroupMembershipRemoval {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipRemoval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupMembershipRemoval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipRemovalList) DeepCopyInto(out *ContactGroupMembershipRemovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContactGroupMembershipRemoval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipRemovalList.
func (in *ContactGroupMembershipRemovalList) DeepCopy() *ContactGroupMembershipRemovalList {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipRemovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactGroupMembershipRemovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipRemovalSpec) DeepCopyInto(out *ContactGroupMembershipRemovalSpec) {
	*out = *in
	out.ContactRef = in.ContactRef
	out.ContactGroupRef = in.ContactGroupRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipRemovalSpec.
func (in *ContactGroupMembershipRemovalSpec) DeepCopy() *ContactGroupMembershipRemovalSpec {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipRemovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipRemovalStatus) DeepCopyInto(out *ContactGroupMembershipRemovalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipRemovalStatus.
func (in *ContactGroupMembershipRemovalStatus) DeepCopy() *ContactGroupMembershipRemovalStatus {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipRemovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipSpec) DeepCopyInto(out *ContactGroupMembershipSpec) {
	*out = *in
	out.ContactRef = in.ContactRef
	out.ContactGroupRef = in.ContactGroupRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipSpec.
func (in *ContactGroupMembershipSpec) DeepCopy() *ContactGroupMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupMembershipStatus) DeepCopyInto(out *ContactGroupMembershipStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ContactProviderStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupMembershipStatus.
func (in *ContactGroupMembershipStatus) DeepCopy() *ContactGroupMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(ContactGroupMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupProviderSpec) DeepCopyInto(out *ContactGroupProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupProviderSpec.
func (in *ContactGroupProviderSpec) DeepCopy() *ContactGroupProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ContactGroupProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupReference) DeepCopyInto(out *ContactGroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupReference.
func (in *ContactGroupReference) DeepCopy() *ContactGroupReference {
	if in == nil {
		return nil
	}
	out := new(ContactGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupSpec) DeepCopyInto(out *ContactGroupSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ContactGroupProviderSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupSpec.
func (in *ContactGroupSpec) DeepCopy() *ContactGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ContactGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactGroupStatus) DeepCopyInto(out *ContactGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ContactProviderStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactGroupStatus.
func (in *ContactGroupStatus) DeepCopy() *ContactGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ContactGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactList) DeepCopyInto(out *ContactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Contact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactList.
func (in *ContactList) DeepCopy() *ContactList {
	if in == nil {
		return nil
	}
	out := new(ContactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactProviderStatus) DeepCopyInto(out *ContactProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactProviderStatus.
func (in *ContactProviderStatus) DeepCopy() *ContactProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ContactProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactReference) DeepCopyInto(out *ContactReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactReference.
func (in *ContactReference) DeepCopy() *ContactReference {
	if in == nil {
		return nil
	}
	out := new(ContactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactSpec) DeepCopyInto(out *ContactSpec) {
	*out = *in
	if in.SubjectRef != nil {
		in, out := &in.SubjectRef, &out.SubjectRef
		*out = new(SubjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactSpec.
func (in *ContactSpec) DeepCopy() *ContactSpec {
	if in == nil {
		return nil
	}
	out := new(ContactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContactStatus) DeepCopyInto(out *ContactStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ContactProviderStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContactStatus.
func (in *ContactStatus) DeepCopy() *ContactStatus {
	if in == nil {
		return nil
	}
	out := new(ContactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Email) DeepCopyInto(out *Email) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Email.
func (in *Email) DeepCopy() *Email {
	if in == nil {
		return nil
	}
	out := new(Email)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Email) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailBroadcast) DeepCopyInto(out *EmailBroadcast) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailBroadcast.
func (in *EmailBroadcast) DeepCopy() *EmailBroadcast {
	if in == nil {
		return nil
	}
	out := new(EmailBroadcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailBroadcast) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailBroadcastList) DeepCopyInto(out *EmailBroadcastList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmailBroadcast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailBroadcastList.
func (in *EmailBroadcastList) DeepCopy() *EmailBroadcastList {
	if in == nil {
		return nil
	}
	out := new(EmailBroadcastList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailBroadcastList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailBroadcastSpec) DeepCopyInto(out *EmailBroadcastSpec) {
	*out = *in
	out.ContactGroupRef = in.ContactGroupRef
	out.TemplateRef = in.TemplateRef
	if in.ScheduledAt != nil {
		in, out := &in.ScheduledAt, &out.ScheduledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailBroadcastSpec.
func (in *EmailBroadcastSpec) DeepCopy() *EmailBroadcastSpec {
	if in == nil {
		return nil
	}
	out := new(EmailBroadcastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailBroadcastStatus) DeepCopyInto(out *EmailBroadcastStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailBroadcastStatus.
func (in *EmailBroadcastStatus) DeepCopy() *EmailBroadcastStatus {
	if in == nil {
		return nil
	}
	out := new(EmailBroadcastStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailList) DeepCopyInto(out *EmailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Email, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailList.
func (in *EmailList) DeepCopy() *EmailList {
	if in == nil {
		return nil
	}
	out := new(EmailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailRecipient) DeepCopyInto(out *EmailRecipient) {
	*out = *in
	out.UserRef = in.UserRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailRecipient.
func (in *EmailRecipient) DeepCopy() *EmailRecipient {
	if in == nil {
		return nil
	}
	out := new(EmailRecipient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailSpec) DeepCopyInto(out *EmailSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	out.Recipient = in.Recipient
	if in.CC != nil {
		in, out := &in.CC, &out.CC
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BCC != nil {
		in, out := &in.BCC, &out.BCC
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]EmailVariable, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailSpec.
func (in *EmailSpec) DeepCopy() *EmailSpec {
	if in == nil {
		return nil
	}
	out := new(EmailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailStatus) DeepCopyInto(out *EmailStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailStatus.
func (in *EmailStatus) DeepCopy() *EmailStatus {
	if in == nil {
		return nil
	}
	out := new(EmailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailTemplate) DeepCopyInto(out *EmailTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailTemplate.
func (in *EmailTemplate) DeepCopy() *EmailTemplate {
	if in == nil {
		return nil
	}
	out := new(EmailTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailTemplateList) DeepCopyInto(out *EmailTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmailTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailTemplateList.
func (in *EmailTemplateList) DeepCopy() *EmailTemplateList {
	if in == nil {
		return nil
	}
	out := new(EmailTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailTemplateSpec) DeepCopyInto(out *EmailTemplateSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]TemplateVariable, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailTemplateSpec.
func (in *EmailTemplateSpec) DeepCopy() *EmailTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(EmailTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailTemplateStatus) DeepCopyInto(out *EmailTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailTemplateStatus.
func (in *EmailTemplateStatus) DeepCopy() *EmailTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(EmailTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailUserReference) DeepCopyInto(out *EmailUserReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailUserReference.
func (in *EmailUserReference) DeepCopy() *EmailUserReference {
	if in == nil {
		return nil
	}
	out := new(EmailUserReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailVariable) DeepCopyInto(out *EmailVariable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailVariable.
func (in *EmailVariable) DeepCopy() *EmailVariable {
	if in == nil {
		return nil
	}
	out := new(EmailVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentContactGroupRef) DeepCopyInto(out *EnrollmentContactGroupRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentContactGroupRef.
func (in *EnrollmentContactGroupRef) DeepCopy() *EnrollmentContactGroupRef {
	if in == nil {
		return nil
	}
	out := new(EnrollmentContactGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentContactSelector) DeepCopyInto(out *EnrollmentContactSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentContactSelector.
func (in *EnrollmentContactSelector) DeepCopy() *EnrollmentContactSelector {
	if in == nil {
		return nil
	}
	out := new(EnrollmentContactSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentTrigger) DeepCopyInto(out *EnrollmentTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentTrigger.
func (in *EnrollmentTrigger) DeepCopy() *EnrollmentTrigger {
	if in == nil {
		return nil
	}
	out := new(EnrollmentTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectReference) DeepCopyInto(out *SubjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectReference.
func (in *SubjectReference) DeepCopy() *SubjectReference {
	if in == nil {
		return nil
	}
	out := new(SubjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateReference) DeepCopyInto(out *TemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateReference.
func (in *TemplateReference) DeepCopy() *TemplateReference {
	if in == nil {
		return nil
	}
	out := new(TemplateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateVariable) DeepCopyInto(out *TemplateVariable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateVariable.
func (in *TemplateVariable) DeepCopy() *TemplateVariable {
	if in == nil {
		return nil
	}
	out := new(TemplateVariable)
	in.DeepCopyInto(out)
	return out
}
