apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - quota-admin.yaml
  - quota-manager.yaml
  - quota-viewer.yaml
  - quota-operator.yaml
  - organization-quota-manager.yaml
  - feature-flag-viewer.yaml
