//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerPortalPlugin) DeepCopyInto(out *ConsumerPortalPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerPortalPlugin.
func (in *ConsumerPortalPlugin) DeepCopy() *ConsumerPortalPlugin {
	if in == nil {
		return nil
	}
	out := new(ConsumerPortalPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsumerPortalPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerPortalPluginList) DeepCopyInto(out *ConsumerPortalPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConsumerPortalPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerPortalPluginList.
func (in *ConsumerPortalPluginList) DeepCopy() *ConsumerPortalPluginList {
	if in == nil {
		return nil
	}
	out := new(ConsumerPortalPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsumerPortalPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerPortalPluginSpec) DeepCopyInto(out *ConsumerPortalPluginSpec) {
	*out = *in
	out.Assets = in.Assets
	out.Visibility = in.Visibility
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerPortalPluginSpec.
func (in *ConsumerPortalPluginSpec) DeepCopy() *ConsumerPortalPluginSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumerPortalPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerPortalPluginStatus) DeepCopyInto(out *ConsumerPortalPluginStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(PluginManifestSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerPortalPluginStatus.
func (in *ConsumerPortalPluginStatus) DeepCopy() *ConsumerPortalPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ConsumerPortalPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginAssets) DeepCopyInto(out *PluginAssets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginAssets.
func (in *PluginAssets) DeepCopy() *PluginAssets {
	if in == nil {
		return nil
	}
	out := new(PluginAssets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginManifestSnapshot) DeepCopyInto(out *PluginManifestSnapshot) {
	*out = *in
	in.FetchedAt.DeepCopyInto(&out.FetchedAt)
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginManifestSnapshot.
func (in *PluginManifestSnapshot) DeepCopy() *PluginManifestSnapshot {
	if in == nil {
		return nil
	}
	out := new(PluginManifestSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginVisibility) DeepCopyInto(out *PluginVisibility) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginVisibility.
func (in *PluginVisibility) DeepCopy() *PluginVisibility {
	if in == nil {
		return nil
	}
	out := new(PluginVisibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPortalPlugin) DeepCopyInto(out *ProviderPortalPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPortalPlugin.
func (in *ProviderPortalPlugin) DeepCopy() *ProviderPortalPlugin {
	if in == nil {
		return nil
	}
	out := new(ProviderPortalPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPortalPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPortalPluginList) DeepCopyInto(out *ProviderPortalPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderPortalPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPortalPluginList.
func (in *ProviderPortalPluginList) DeepCopy() *ProviderPortalPluginList {
	if in == nil {
		return nil
	}
	out := new(ProviderPortalPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPortalPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPortalPluginSpec) DeepCopyInto(out *ProviderPortalPluginSpec) {
	*out = *in
	out.Assets = in.Assets
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPortalPluginSpec.
func (in *ProviderPortalPluginSpec) DeepCopy() *ProviderPortalPluginSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderPortalPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPortalPluginStatus) DeepCopyInto(out *ProviderPortalPluginStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(PluginManifestSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPortalPluginStatus.
func (in *ProviderPortalPluginStatus) DeepCopy() *ProviderPortalPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderPortalPluginStatus)
	in.DeepCopyInto(out)
	return out
}
