apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: milo-controller-manager
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milo-controller-manager
      app.kubernetes.io/part-of: milo-control-plane
