apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: milo-iam-resource-metrics
    files:
    - users.yaml
    - groups.yaml
    - group_memberships.yaml
    - service_accounts.yaml
    - policy_bindings.yaml
    - roles.yaml
    - user_invitations.yaml
    - protected_resources.yaml
    options:
      labels:
        telemetry.datumapis.com/core-resource-metrics-config: "true"
