kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "iam.miloapis.com"
        kind: "User"
        version: "v1alpha1"
      labelsFromPath:
        name: [metadata, name]
        namespace: [metadata, namespace]
        email: [spec, email]
      metricNamePrefix: milo_users
      metrics:
        - name: "info"
          each:
            type: Info
            info:
              labelsFromPath:
                "uid": [metadata, uid]
                email: [spec, email]
                state: [status, state]
        - name: "created_timestamp"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]
        - name: "status_condition"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: ["type"]
                reason: ["reason"]
              valueFrom: ["status"]
        - name: "status_condition_last_transition_time"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: ["type"]
                reason: ["reason"]
                status: ["status"]
              valueFrom: ["lastTransitionTime"]
