apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

sortOptions:
  order: fifo

resources:
  - clusternote-claim-policy.yaml
  - configmap-claim-policy.yaml
  - note-claim-policy.yaml
  - secret-claim-policy.yaml
