package v1alpha1

import (
	"context"
	"net/url"
	"regexp"
	"strings"

	"k8s.io/apimachinery/pkg/util/validation/field"
	utilfeature "k8s.io/apiserver/pkg/util/feature"

	resourcemanagerv1alpha1 "go.miloapis.com/milo/pkg/apis/resourcemanager/v1alpha1"
	"go.miloapis.com/milo/pkg/features"
)

func unifiedOrganizationsEnabled() bool {
	return utilfeature.DefaultFeatureGate.Enabled(features.UnifiedOrganizations)
}

// websiteSchemeRE matches a leading URL scheme (e.g. "https://", "ftp://").
var websiteSchemeRE = regexp.MustCompile(`(?i)^[a-z][a-z0-9+.-]*://`)

// normalizeWebsite trims whitespace and, if the value has no scheme, adds
// "https://" so a bare domain like "example.com" can be parsed and validated
// as a URL.
func normalizeWebsite(website string) string {
	website = strings.TrimSpace(website)
	if website == "" || websiteSchemeRE.MatchString(website) {
		return website
	}
	return "https://" + website
}

// sanitizeOrganizationContactInfo normalizes free-form contact fields in
// place before validation runs.
func sanitizeOrganizationContactInfo(contact *resourcemanagerv1alpha1.OrganizationContactInfo) {
	if contact == nil {
		return
	}
	contact.Website = normalizeWebsite(contact.Website)
}

func validateOrganizationContactInfo(contact *resourcemanagerv1alpha1.OrganizationContactInfo, fldPath *field.Path) field.ErrorList {
	if contact == nil {
		return nil
	}

	var allErrs field.ErrorList

	if strings.TrimSpace(contact.Email) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("email"), "email is required when contactInfo is set"))
	}

	if strings.TrimSpace(contact.Name) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("name"), "name is required when contactInfo is set"))
	}

	if contact.Address != nil && strings.TrimSpace(contact.Address.Country) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("address", "country"), "country is required when address is set"))
	}

	// Validate against the normalized form so a bare domain (e.g.
	// "example.com") is treated the same as "https://example.com", whether
	// or not the mutating webhook has already normalized it.
	if website := normalizeWebsite(contact.Website); website != "" {
		parsed, err := url.ParseRequestURI(website)
		if err != nil || parsed.Host == "" {
			allErrs = append(allErrs, field.Invalid(fldPath.Child("website"), contact.Website, `must be a valid website, e.g. "example.com" or "https://example.com"`))
		}
	}

	return allErrs
}

func validateOrganizationSpec(spec *resourcemanagerv1alpha1.OrganizationSpec, fldPath *field.Path) field.ErrorList {
	if spec == nil {
		return nil
	}

	var allErrs field.ErrorList
	allErrs = append(allErrs, validateOrganizationContactInfo(spec.ContactInfo, fldPath.Child("contactInfo"))...)

	if !unifiedOrganizationsEnabled() {
		switch spec.Type {
		case "":
			allErrs = append(allErrs, field.Required(fldPath.Child("type"), "type is required"))
		case resourcemanagerv1alpha1.OrganizationTypePersonal, resourcemanagerv1alpha1.OrganizationTypeStandard:
		default:
			allErrs = append(allErrs, field.NotSupported(
				fldPath.Child("type"),
				spec.Type,
				[]string{resourcemanagerv1alpha1.OrganizationTypePersonal, resourcemanagerv1alpha1.OrganizationTypeStandard},
			))
		}
	}

	return allErrs
}

func validateOrganizationUpdate(oldOrg, newOrg *resourcemanagerv1alpha1.Organization) field.ErrorList {
	var allErrs field.ErrorList
	allErrs = append(allErrs, validateOrganizationSpec(&newOrg.Spec, field.NewPath("spec"))...)

	if unifiedOrganizationsEnabled() {
		if oldOrg.Spec.ContactInfo != nil && newOrg.Spec.ContactInfo == nil {
			allErrs = append(allErrs, field.Invalid(field.NewPath("spec", "contactInfo"), nil, "contactInfo cannot be removed once set"))
		}
		return allErrs
	}

	if oldOrg.Spec.Type != newOrg.Spec.Type {
		allErrs = append(allErrs, field.Forbidden(field.NewPath("spec", "type"), "organization type is immutable"))
	}

	return allErrs
}

func organizationGenerateNamePrefix() string {
	return "org-"
}

func isOrganizationAutoGeneratedName(name string) bool {
	return strings.HasPrefix(name, organizationGenerateNamePrefix())
}

func ensureOrganizationGenerateName(ctx context.Context, org *resourcemanagerv1alpha1.Organization) error {
	if org.Name != "" || org.GenerateName != "" {
		return nil
	}
	org.GenerateName = organizationGenerateNamePrefix()
	return nil
}
