package v1alpha1

import (
	"context"
	"strings"

	"k8s.io/apimachinery/pkg/util/validation/field"

	resourcemanagerv1alpha1 "go.miloapis.com/milo/pkg/apis/resourcemanager/v1alpha1"
)

func validateOrganizationContactInfo(contact *resourcemanagerv1alpha1.OrganizationContactInfo, fldPath *field.Path) field.ErrorList {
	if contact == nil {
		return nil
	}

	var allErrs field.ErrorList

	if strings.TrimSpace(contact.Email) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("email"), "email is required when contactInfo is set"))
	}

	if strings.TrimSpace(contact.Name) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("name"), "name is required when contactInfo is set"))
	}

	if contact.Address != nil && strings.TrimSpace(contact.Address.Country) == "" {
		allErrs = append(allErrs, field.Required(fldPath.Child("address", "country"), "country is required when address is set"))
	}

	return allErrs
}

func validateOrganizationSpec(spec *resourcemanagerv1alpha1.OrganizationSpec, fldPath *field.Path) field.ErrorList {
	if spec == nil {
		return nil
	}
	return validateOrganizationContactInfo(spec.ContactInfo, fldPath.Child("contactInfo"))
}

func validateOrganizationUpdate(oldOrg, newOrg *resourcemanagerv1alpha1.Organization) field.ErrorList {
	var allErrs field.ErrorList
	allErrs = append(allErrs, validateOrganizationSpec(&newOrg.Spec, field.NewPath("spec"))...)

	if oldOrg.Spec.ContactInfo != nil && newOrg.Spec.ContactInfo == nil {
		allErrs = append(allErrs, field.Invalid(field.NewPath("spec", "contactInfo"), nil, "contactInfo cannot be removed once set"))
	}

	return allErrs
}

func organizationGenerateNamePrefix() string {
	return "org-"
}

func isOrganizationAutoGeneratedName(name string) bool {
	return strings.HasPrefix(name, organizationGenerateNamePrefix())
}

func ensureOrganizationGenerateName(ctx context.Context, org *resourcemanagerv1alpha1.Organization) error {
	if org.Name != "" || org.GenerateName != "" {
		return nil
	}
	org.GenerateName = organizationGenerateNamePrefix()
	return nil
}
