package v1alpha1

import (
	"context"
	"fmt"
	"slices"
	"strings"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/util/validation/field"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	resourcemanagercontroller "go.miloapis.com/milo/internal/controllers/resourcemanager"
	iamv1alpha1 "go.miloapis.com/milo/pkg/apis/iam/v1alpha1"
	resourcemanagerv1alpha1 "go.miloapis.com/milo/pkg/apis/resourcemanager/v1alpha1"
)

// log is for logging in this package.
var organizationlog = logf.Log.WithName("organization-resource")

// SetupWebhooksWithManager sets up all resourcemanager.miloapis.com webhooks
func SetupOrganizationWebhooksWithManager(mgr ctrl.Manager, systemNamespace string, organizationOwnerRoleName string, organizationOwnerRoleNamespace string) error {
	organizationlog.Info("Setting up resourcemanager.miloapis.com organization webhooks")

	return ctrl.NewWebhookManagedBy(mgr, &resourcemanagerv1alpha1.Organization{}).
		WithValidator(&OrganizationValidator{
			client:             mgr.GetClient(),
			systemNamespace:    systemNamespace,
			ownerRoleName:      organizationOwnerRoleName,
			ownerRoleNamespace: organizationOwnerRoleNamespace,
		}).
		WithDefaulter(&OrganizationMutator{}).
		Complete()
}

// +kubebuilder:webhook:path=/mutate-resourcemanager-miloapis-com-v1alpha1-organization,mutating=true,failurePolicy=fail,sideEffects=NoneOnDryRun,groups=resourcemanager.miloapis.com,resources=organizations,verbs=create,versions=v1alpha1,name=morganization.datum.net,admissionReviewVersions={v1,v1beta1},serviceName=milo-controller-manager,servicePort=9443,serviceNamespace=milo-system

// OrganizationMutator defaults organization create requests.
type OrganizationMutator struct{}

func (m *OrganizationMutator) Default(ctx context.Context, org *resourcemanagerv1alpha1.Organization) error {
	if !unifiedOrganizationsEnabled() {
		return nil
	}

	req, err := admission.RequestFromContext(ctx)
	if err != nil {
		return fmt.Errorf("failed to get request from context: %w", err)
	}

	if slices.Contains(req.UserInfo.Groups, "system:masters") {
		return nil
	}

	org.Spec.Type = ""
	if err := ensureOrganizationGenerateName(ctx, org); err != nil {
		return err
	}

	if org.Annotations == nil {
		org.Annotations = map[string]string{}
	}
	org.Annotations[resourcemanagerv1alpha1.OrganizationCreatorUserUIDAnnotation] = string(req.UserInfo.UID)
	return nil
}

// +kubebuilder:webhook:path=/validate-resourcemanager-miloapis-com-v1alpha1-organization,mutating=false,failurePolicy=fail,sideEffects=NoneOnDryRun,groups=resourcemanager.miloapis.com,resources=organizations,verbs=create;update,versions=v1alpha1,name=vorganization.datum.net,admissionReviewVersions={v1,v1beta1},serviceName=milo-controller-manager,servicePort=9443,serviceNamespace=milo-system

// OrganizationValidator validates Organizations
type OrganizationValidator struct {
	client             client.Client
	decoder            admission.Decoder
	systemNamespace    string
	ownerRoleName      string
	ownerRoleNamespace string
}

func (v *OrganizationValidator) ValidateCreate(ctx context.Context, org *resourcemanagerv1alpha1.Organization) (admission.Warnings, error) {
	organizationlog.Info("Validating Organization", "name", org.Name)

	errs := validateOrganizationSpec(&org.Spec, field.NewPath("spec"))
	if len(org.Name) > 50 {
		errs = append(errs, field.Invalid(
			field.NewPath("metadata", "name"),
			org.Name,
			"name exceeds maximum length of 50 characters. Choose a shorter name and try again",
		))
	}

	req, err := admission.RequestFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get request from context: %w", err)
	}

	if !slices.Contains(req.UserInfo.Groups, "system:masters") && unifiedOrganizationsEnabled() {
		if org.Name != "" && !isOrganizationAutoGeneratedName(org.Name) {
			errs = append(errs, field.Invalid(
				field.NewPath("metadata", "name"),
				org.Name,
				"organization names must be system-assigned; create the organization with generateName prefix org-",
			))
		}
		if org.Name == "" && org.GenerateName != "" && !strings.HasPrefix(org.GenerateName, organizationGenerateNamePrefix()) {
			errs = append(errs, field.Invalid(
				field.NewPath("metadata", "generateName"),
				org.GenerateName,
				fmt.Sprintf("generateName must use prefix %q", organizationGenerateNamePrefix()),
			))
		}
	}

	if len(errs) > 0 {
		return nil, apierrors.NewInvalid(
			resourcemanagerv1alpha1.Kind("Organization"),
			org.Name,
			errs,
		)
	}

	// Don't create namespace or organization membership for dry run requests.
	if req.DryRun != nil && *req.DryRun {
		return nil, nil
	}

	// generateName creates are reconciled after the apiserver assigns a name.
	if org.Name == "" {
		return nil, nil
	}

	// Create namespace and owner membership on Organization Create operation.
	if err := resourcemanagercontroller.EnsureOrganizationNamespace(ctx, v.client, org); err != nil {
		return nil, fmt.Errorf("failed to create organization namespace: %w", err)
	}

	// Organizations created by system:masters shouldn't have an organization
	// membership created because they're creating the organization for another
	// user in the system. It's expected those organizations will create the
	// necessary organization membership to provide the user access.
	//
	// TODO: Convert this to use a SubjectAccessReview to check if the user has
	//       permission to create an organization without an organization membership.
	if slices.Contains(req.UserInfo.Groups, "system:masters") {
		return nil, nil
	}

	// Look up the user in the iam API
	user, err := v.lookupUser(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to lookup user: %w", err)
	}

	// Create OrganizationMembership with owner role for the organization owner
	if err := resourcemanagercontroller.EnsureOwnerOrganizationMembership(
		ctx,
		v.client,
		org,
		user,
		v.ownerRoleName,
		v.ownerRoleNamespace,
	); err != nil {
		return nil, fmt.Errorf("failed to create organization membership: %w", err)
	}

	return nil, nil
}

func (v *OrganizationValidator) ValidateUpdate(ctx context.Context, oldObj, newOrg *resourcemanagerv1alpha1.Organization) (admission.Warnings, error) {
	errs := validateOrganizationUpdate(oldObj, newOrg)

	// Validate organization name length
	if len(newOrg.Name) > 50 {
		errs = append(errs, field.Invalid(
			field.NewPath("metadata", "name"),
			newOrg.Name,
			"name exceeds maximum length of 50 characters. Choose a shorter name and try again",
		))
	}

	if len(errs) > 0 {
		return nil, apierrors.NewInvalid(
			resourcemanagerv1alpha1.Kind("Organization"),
			newOrg.Name,
			errs,
		)
	}

	return nil, nil
}

func (v *OrganizationValidator) ValidateDelete(ctx context.Context, obj *resourcemanagerv1alpha1.Organization) (admission.Warnings, error) {
	return nil, nil
}

// lookupUser retrieves the User resource from the iam.miloapis.com API
func (v *OrganizationValidator) lookupUser(ctx context.Context) (*iamv1alpha1.User, error) {
	req, err := admission.RequestFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get request from context: %w", err)
	}

	foundUser := &iamv1alpha1.User{}
	if err := v.client.Get(ctx, client.ObjectKey{Name: string(req.UserInfo.UID)}, foundUser); err != nil {
		return nil, fmt.Errorf("failed to get user '%s' from iam.miloapis.com API: %w", string(req.UserInfo.UID), err)
	}

	return foundUser, nil
}
