apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: identity.miloapis.com-serviceaccountkey
spec:
  serviceRef:
    name: "identity.miloapis.com"
  kind: ServiceAccountKey
  plural: serviceaccountkeys
  singular: serviceaccountkey
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
