apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-access-approvals-editor
  annotations:
    kubernetes.io/display-name: Platform Access Approval Editor
    kubernetes.io/description: Create, update, and delete platform access approvals
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-platform-access-approvals-reader
  includedPermissions:
    - iam.miloapis.com/platformaccessapprovals.create
    - iam.miloapis.com/platformaccessapprovals.update
    - iam.miloapis.com/platformaccessapprovals.patch
    - iam.miloapis.com/platformaccessapprovals.delete
