apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-service-accounts-admin
  annotations:
    kubernetes.io/display-name: IAM Service Accounts Admin
    kubernetes.io/description: "Full access to service accounts."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-service-accounts-editor
