apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-invitations-editor
  annotations:
    kubernetes.io/display-name: Platform Invitation Editor
    kubernetes.io/description: Create, update, and delete platform invitations
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-platform-invitations-reader
  includedPermissions:
    - iam.miloapis.com/platforminvitations.create
    - iam.miloapis.com/platforminvitations.update
    - iam.miloapis.com/platforminvitations.patch
    - iam.miloapis.com/platforminvitations.delete


