apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-service-accounts-viewer
  annotations:
    kubernetes.io/display-name: IAM Service Accounts Viewer
    kubernetes.io/description: "Allows viewing service accounts."
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/serviceaccounts.get
    - iam.miloapis.com/serviceaccounts.list
    - iam.miloapis.com/serviceaccounts.watch
