apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-access-rejections-reader
  annotations:
    kubernetes.io/display-name: Platform Access Rejection Viewer
    kubernetes.io/description: View platform access rejections
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/platformaccessrejections.get
    - iam.miloapis.com/platformaccessrejections.list
    - iam.miloapis.com/platformaccessrejections.watch
