apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: role-editor
  annotations:
    kubernetes.io/display-name: Role Editor
    kubernetes.io/description: Create, update, and delete IAM roles
spec:
  launchStage: Beta
  inheritedRoles:
    - name: role-reader
  includedPermissions:
    - iam.miloapis.com/roles.create
    - iam.miloapis.com/roles.update
    - iam.miloapis.com/roles.patch
    - iam.miloapis.com/roles.delete
