apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-access-approvals-admin
  annotations:
    kubernetes.io/display-name: Platform Access Approval Admin
    kubernetes.io/description: Full access to platform access approvals
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-platform-access-approvals-editor
