apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-user-deactivations-reader
  annotations:
    kubernetes.io/display-name: User Deactivation Viewer
    kubernetes.io/description: View user deactivations
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/userdeactivations.get
    - iam.miloapis.com/userdeactivations.list
    - iam.miloapis.com/userdeactivations.watch
