apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: role-reader
  annotations:
    kubernetes.io/display-name: Role Viewer
    kubernetes.io/description: View IAM roles
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/roles.get
    - iam.miloapis.com/roles.list
    - iam.miloapis.com/roles.watch
