apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-user-invitations-reader
  annotations:
    kubernetes.io/display-name: User Invitation Viewer
    kubernetes.io/description: View user invitations
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/userinvitations.get
    - iam.miloapis.com/userinvitations.list
    - iam.miloapis.com/userinvitations.watch
