apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-service-accounts-editor
  annotations:
    kubernetes.io/display-name: IAM Service Accounts Editor
    kubernetes.io/description: "Allows editing service accounts."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-service-accounts-viewer
  includedPermissions:
    - iam.miloapis.com/serviceaccounts.create
    - iam.miloapis.com/serviceaccounts.update
    - iam.miloapis.com/serviceaccounts.patch
    - iam.miloapis.com/serviceaccounts.delete
