apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-accesses-reader
  annotations:
    kubernetes.io/display-name: Platform Access Viewer
    kubernetes.io/description: View platform accesses
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/platformaccesses.get
    - iam.miloapis.com/platformaccesses.list
    - iam.miloapis.com/platformaccesses.watch
