apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-access-rejections-editor
  labels:
    taxonomy.miloapis.com/role-category: service
  annotations:
    kubernetes.io/display-name: Platform Access Rejection Editor
    kubernetes.io/description: Create, update, and delete platform access rejections
    taxonomy.miloapis.com/product: Identity & Access Management
    taxonomy.miloapis.com/sort-order: "20"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-platform-access-rejections-reader
  includedPermissions:
    - iam.miloapis.com/platformaccessrejections.create
    - iam.miloapis.com/platformaccessrejections.update
    - iam.miloapis.com/platformaccessrejections.patch
    - iam.miloapis.com/platformaccessrejections.delete
