apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam.miloapis.com-acceptinvitation
  annotations:
    kubernetes.io/display-name: Accept Invitation
    kubernetes.io/description: Accept user invitations to join organizations
spec:
  launchStage: Beta
  includedPermissions:
  - iam.miloapis.com/userinvitations.update
  - iam.miloapis.com/userinvitations.patch
