apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam.miloapis.com-acceptinvitation
  labels:
    taxonomy.miloapis.com/role-category: service
  annotations:
    kubernetes.io/display-name: Accept Invitation
    kubernetes.io/description: Accept user invitations to join organizations
    taxonomy.miloapis.com/product: Identity & Access Management
    taxonomy.miloapis.com/sort-order: "40"
spec:
  launchStage: Beta
  includedPermissions:
  - iam.miloapis.com/userinvitations.update
  - iam.miloapis.com/userinvitations.patch
