apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-service-account-keys-editor
  annotations:
    kubernetes.io/display-name: Identity Service Account Keys Editor
    kubernetes.io/description: "Allows editing service account keys."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: identity-service-account-keys-viewer
  includedPermissions:
    - identity.miloapis.com/serviceaccountkeys.create
    - identity.miloapis.com/serviceaccountkeys.update
    - identity.miloapis.com/serviceaccountkeys.patch
    - identity.miloapis.com/serviceaccountkeys.delete
