apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-service-account-keys-admin
  annotations:
    kubernetes.io/display-name: Identity Service Account Keys Admin
    kubernetes.io/description: "Full access to service account keys."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: identity-service-account-keys-editor
