apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-service-account-keys-viewer
  annotations:
    kubernetes.io/display-name: Identity Service Account Keys Viewer
    kubernetes.io/description: "Allows viewing service account keys."
spec:
  launchStage: Beta
  includedPermissions:
    - identity.miloapis.com/serviceaccountkeys.get
    - identity.miloapis.com/serviceaccountkeys.list
    - identity.miloapis.com/serviceaccountkeys.watch
