apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-contact-group-membership-removal-reader
  labels:
    taxonomy.miloapis.com/role-category: feature
  annotations:
    kubernetes.io/display-name: Contact Group Membership Removal Viewer
    kubernetes.io/description: View notification contact group membership removals
    taxonomy.miloapis.com/product: Notifications
    taxonomy.miloapis.com/sort-order: "30"
spec:
  launchStage: Beta
  includedPermissions:
    - notification.miloapis.com/contactgroupmembershipremovals.get
    - notification.miloapis.com/contactgroupmembershipremovals.list
    - notification.miloapis.com/contactgroupmembershipremovals.watch
