apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-email-reader
  labels:
    taxonomy.miloapis.com/role-category: feature
  annotations:
    kubernetes.io/display-name: Notification Email Viewer
    kubernetes.io/description: View notification emails
    taxonomy.miloapis.com/product: Notifications
    taxonomy.miloapis.com/sort-order: "30"
spec:
  launchStage: Beta
  includedPermissions:
    # Read-only permissions for Email resources
    - notification.miloapis.com/emails.get
    - notification.miloapis.com/emails.list
    - notification.miloapis.com/emails.watch
