apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-contact-group-reader
  annotations:
    kubernetes.io/display-name: Notification Contact Group Viewer
    kubernetes.io/description: View notification contact groups
spec:
  launchStage: Beta
  includedPermissions:
    - notification.miloapis.com/contactgroups.get
    - notification.miloapis.com/contactgroups.list
    - notification.miloapis.com/contactgroups.watch
