apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-email-admin
  annotations:
    kubernetes.io/display-name: Notification Email Admin
    kubernetes.io/description: Full access to notification emails
spec:
  launchStage: Beta
  inheritedRoles:
    - name: notification-email-creator
