apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-email-broadcast-creator
  labels:
    taxonomy.miloapis.com/role-category: feature
  annotations:
    kubernetes.io/display-name: Email Broadcast Creator
    kubernetes.io/description: Create and delete email broadcasts
    taxonomy.miloapis.com/product: Notifications
    taxonomy.miloapis.com/sort-order: "20"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: notification-email-broadcast-reader
  includedPermissions:
    - notification.miloapis.com/emailbroadcasts.create
    - notification.miloapis.com/emailbroadcasts.delete
