apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-contact-group-membership-removal-admin
  annotations:
    kubernetes.io/display-name: Contact Group Membership Removal Admin
    kubernetes.io/description: Full access to notification contact group membership removals
spec:
  launchStage: Beta
  inheritedRoles:
    - name: notification-contact-group-membership-removal-editor
