apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-contact-group-reader
  labels:
    taxonomy.miloapis.com/role-category: feature
  annotations:
    kubernetes.io/display-name: Notification Contact Group Viewer
    kubernetes.io/description: View notification contact groups
    taxonomy.miloapis.com/product: Notifications
    taxonomy.miloapis.com/sort-order: "30"
spec:
  launchStage: Beta
  includedPermissions:
    - notification.miloapis.com/contactgroups.get
    - notification.miloapis.com/contactgroups.list
    - notification.miloapis.com/contactgroups.watch
