apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: notification-email-broadcast-reader
  labels:
    taxonomy.miloapis.com/role-category: feature
  annotations:
    kubernetes.io/display-name: Email Broadcast Viewer
    kubernetes.io/description: View email broadcasts
    taxonomy.miloapis.com/product: Notifications
    taxonomy.miloapis.com/sort-order: "30"
spec:
  launchStage: Beta
  includedPermissions:
    # Read-only permissions for EmailBroadcast resources
    - notification.miloapis.com/emailbroadcasts.get
    - notification.miloapis.com/emailbroadcasts.list
    - notification.miloapis.com/emailbroadcasts.watch
