apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: owner
  labels:
    taxonomy.miloapis.com/role-category: platform
  annotations:
    kubernetes.io/display-name: Owner
    kubernetes.io/description: Full access to all platform resources including resource management, IAM, and core platform
    taxonomy.miloapis.com/product: Access Everything
    taxonomy.miloapis.com/sort-order: "10"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: resourcemanager-admin
    - name: iam-admin
    - name: core-admin
    - name: apiextensions-reader
