# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-user-self-manage
spec:
  inheritedRoles:
    - name: activity.miloapis.com-audit-log-querier
