name: Build and Publish Docker Image

on:
  push:
  release:
    types: ["published"]

jobs:
  publish-container-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.8.1
    with:
      registry-organization: milo-os
      image-name: milo
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  publish-kustomize-bundles:
    # Add explicit dependency so that the kustomize bundles only get published
    # if the container image has been built successfully. This helps prevent
    # situations where the deployment manifests are picked up by flux but the
    # container is still being created.
    needs: [publish-container-image]
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.8.1
    with:
      bundle-name: ghcr.io/milo-os/milo-kustomize
      bundle-path: config
      image-overlays: config/apiserver,config/controller-manager/base
      image-name: ghcr.io/milo-os/milo
    secrets: inherit